# Generated by Django 3.2.6 on 2021-08-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=36)),
                ('period_of_reg', models.DurationField()),
                ('verified_contact', models.JSONField()),
            ],
        ),
    ]
